/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Beans.Pessoa;
import Dao.PessoaDao;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class EditarExcluir extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarExcluir.class.getName());

    /**
     * Creates new form EditarExcluir
     */
    public EditarExcluir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BntGrp_Sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Bnt_Atualizar = new javax.swing.JButton();
        TextF_idOcult = new javax.swing.JTextField();
        TextF_id = new javax.swing.JTextField();
        TextF_Nome = new javax.swing.JTextField();
        Bnt_Consultar = new javax.swing.JButton();
        BntExcluir = new javax.swing.JButton();
        Rdo_M = new javax.swing.JRadioButton();
        Rdo_F = new javax.swing.JRadioButton();
        Cmb_Idioma = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("editar e excluir pessoa:");

        jLabel2.setText("id");

        jLabel3.setText("id");

        jLabel4.setText("Nome:");

        jLabel5.setText("Sexo:");

        jLabel6.setText("idioma:");

        Bnt_Atualizar.setText("Atualizar");
        Bnt_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_AtualizarActionPerformed(evt);
            }
        });

        TextF_idOcult.setEditable(false);
        TextF_idOcult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextF_idOcultActionPerformed(evt);
            }
        });

        TextF_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextF_idActionPerformed(evt);
            }
        });

        Bnt_Consultar.setText("Consultar");
        Bnt_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bnt_ConsultarActionPerformed(evt);
            }
        });

        BntExcluir.setText("excluir");
        BntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntExcluirActionPerformed(evt);
            }
        });

        BntGrp_Sexo.add(Rdo_M);
        Rdo_M.setText("Maculino");

        BntGrp_Sexo.add(Rdo_F);
        Rdo_F.setText("Feminino");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextF_idOcult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextF_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextF_Nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Cmb_Idioma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Rdo_M, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Rdo_F)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bnt_Atualizar)
                    .addComponent(Bnt_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextF_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bnt_Consultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextF_idOcult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Rdo_M)
                    .addComponent(Rdo_F))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cmb_Idioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BntExcluir)
                    .addComponent(Bnt_Atualizar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bnt_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_AtualizarActionPerformed
        if (TextF_idOcult.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Consulte uma pessoa antes de tentar atualizar!");
        return;
    }

    String sexo = null;
    if (Rdo_M.isSelected()) {
        sexo = "M";
    } else if (Rdo_F.isSelected()) {
        sexo = "F";
    }

    Pessoa p = new Pessoa();
    p.setId(Integer.parseInt(TextF_idOcult.getText()));
    p.setNome(TextF_Nome.getText());
    p.setSexo(sexo);
    p.setIdioma(Cmb_Idioma.getSelectedItem().toString());

    PessoaDao pDAO = new PessoaDao();
    pDAO.editar(p);

    JOptionPane.showMessageDialog(this, "Registro atualizado com sucesso!");
    limparFormulario();
    }//GEN-LAST:event_Bnt_AtualizarActionPerformed

    private void TextF_idOcultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextF_idOcultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextF_idOcultActionPerformed

    private void TextF_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextF_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextF_idActionPerformed

    private void Bnt_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bnt_ConsultarActionPerformed
       try {
        int idPessoa = Integer.parseInt(TextF_id.getText());
        PessoaDao pDAO = new PessoaDao();
        Pessoa p = pDAO.getPessoa(idPessoa);
        
        if (p == null) {
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Pessoa não encontrada!");
        } else {
            TextF_idOcult.setText(String.valueOf(p.getId()));
            TextF_Nome.setText(p.getNome());
            
            if ("M".equalsIgnoreCase(p.getSexo())) {
                Rdo_M.setSelected(true);
            } else if ("F".equalsIgnoreCase(p.getSexo())) {
                Rdo_F.setSelected(true);
            }
            
            Cmb_Idioma.setSelectedItem(p.getIdioma());
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Informe um ID válido para consulta!");
    }
    }//GEN-LAST:event_Bnt_ConsultarActionPerformed

    private void BntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntExcluirActionPerformed
       if (TextF_idOcult.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Consulte uma pessoa antes de excluir!");
        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
        this, 
        "Deseja realmente excluir?", 
        "Exclusão", 
        JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        int id = Integer.parseInt(TextF_idOcult.getText());
        PessoaDao pDAO = new PessoaDao();
        pDAO.excluir(id);

        JOptionPane.showMessageDialog(this, "Pessoa excluída com sucesso!");
        limparFormulario();
    }
    }//GEN-LAST:event_BntExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EditarExcluir().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntExcluir;
    private javax.swing.ButtonGroup BntGrp_Sexo;
    private javax.swing.JButton Bnt_Atualizar;
    private javax.swing.JButton Bnt_Consultar;
    private javax.swing.JComboBox<String> Cmb_Idioma;
    private javax.swing.JRadioButton Rdo_F;
    private javax.swing.JRadioButton Rdo_M;
    private javax.swing.JTextField TextF_Nome;
    private javax.swing.JTextField TextF_id;
    private javax.swing.JTextField TextF_idOcult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

private void limparFormulario() {
    TextF_id.setText("");
    TextF_idOcult.setText("");
    TextF_Nome.setText("");
    BntGrp_Sexo.clearSelection();
    Cmb_Idioma.setSelectedIndex(0);
}
 }
